davide32123/farm-me

Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20200711055804_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
I installed the devise gem, done the configuration needed to make it run (on development environment only), generated the user model with devise and added a few data relevant to our application
@Ayasunsun can you review this PR?
=> user model with devise gem

Gemfile
@cassianotadaoyasumitsu for validation
=> updated ruby version on gem file as well

config/environments/production.rb
@Ayasunsun can you review this PR and merge if ok?
=> Devise gem configuration for prod

config/routes.rb
@Ayasunsun for review and merge
=> create routes based on Farmer User Story Excel file

app/controllers/baskets_controller.rb, app/controllers/farmers_controller.rb, app/controllers/subscriptions_controller.rb, test/controllers/baskets_controller_test.rb, test/controllers/farmers_controller_test.rb, test/controllers/subscriptions_controller_test.rb
@cassianotadaoyasumitsu for review
=> generated controllers

app/models/basket.rb, app/models/basket_item.rb, app/models/product.rb, app/models/subscription.rb, app/models/user.rb
Added normal validations, although unsure how much we would want to ensure was present. 
Added scope to the subscription and BasketItem so that it ensures both have uniqueness when comparing basket_id/user_id and basket_id/product_id.
=> Added validations to models

Gemfile, Gemfile.lock, app/controllers/baskets_controller.rb, app/models/basket.rb, app/views/baskets/_form.html.erb, app/views/baskets/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20200714114658_create_active_storage_tables.active_storage.rb, db/schema.rb
add photos: [] in basket_params
@JupitersLB @davide32123 @Ayasunsun
=> baskets/new and Cloudinary

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/policies/application_policy.rb, app/policies/basket_policy.rb, app/policies/subscription_policy.rb, test/policies/basket_policy_test.rb, test/policies/subscription_policy_test.rb
=> pundit installation

app/controllers/baskets_controller.rb, app/views/baskets/show.html.erb
=> basic basket show page

app/controllers/baskets_controller.rb, app/policies/basket_policy.rb, db/seeds.rb
Updated pundit and seed file
Created users for each of us with name.surname@farm-me.com and password "password"
=> Realistic seed

config/environments/production.rb
Cloudinary in production only
@davide32123
=> Cloudinary

app/views/farmers/index.html.erb, app/views/pages/farmers.html.erb
I've added a basket list to the dashboard. I will create the subscription part separately. some refactoring is needed for sure🧐
=> Dashboard view page

app/controllers/farmers_controller.rb, app/policies/basket_policy.rb, app/policies/farmer_policy.rb, app/policies/subscription_policy.rb
All working. Still need a subscriptions_path.
=> Current user for farmer controller

app/controllers/pages_controller.rb
=> no need to login for homepage

app/policies/basket_policy.rb, app/views/baskets/show.html.erb
In the end no JS but collapse and added authorization as well
=> Add new product js

app/assets/stylesheets/components/_basketcards.scss, app/assets/stylesheets/components/_index.scss, app/views/farmers/index.html.erb, app/views/shared/_orderlist.html.erb, db/seeds.rb
farmer cards can scroll endlessly left and right
=> Sidescroll cards

app/assets/stylesheets/components/_subscriptionlist.scss, app/assets/stylesheets/config/_colors.scss
=> typo fixed

app/views/baskets/show.html.erb
Fixed main Photo in the show page
=> fix main photo

app/assets/stylesheets/components/_footer.scss
=> footer fixed

app/models/subscription.rb, db/migrate/20200721103455_change_data_type_for_subscription_delivery_day.rb, db/schema.rb, db/seeds.rb
Updated as per description and seed file accordingly. Need to db:migrate and db:seed after this change
=> change subscription delivery_date into string and allow weekdays only

app/controllers/subscriptions_controller.rb, app/policies/subscription_policy.rb, app/views/baskets/show.html.erb
Please check the changes to make the subscription button work, I started this branch before the changes in date where merged so after this PR is also approved I will change the choice to be a drop-down list with the days of the week
=> make subscribe button work

app/views/baskets/show.html.erb
=> limit days selection for subscription

app/views/baskets/show.html.erb
For review, I grey out the button if current user has already a subscription to displayed basked
=> avoid double subscription to basket

app/controllers/baskets_controller.rb, app/helpers/application_helper.rb, app/javascript/packs/application.js, app/models/basket.rb, app/models/basket_item.rb, app/views/baskets/_basket_item.html.erb, app/views/baskets/_form.html.erb
Frontend apart, it seems to be working well
=> Nested attributes

app/helpers/application_helper.rb, app/javascript/packs/application.js, app/views/baskets/_basket_item.html.erb, app/views/baskets/_form.html.erb
Some hacky stuff but it works, style is better but not ideal
=> Basket details style
